version: '3.8'

services:
  app-db:
    image: postgres:15-alpine
    container_name: vietnam_agri_db
    environment:
      POSTGRES_USER: vietnamagriculture
      POSTGRES_PASSWORD: vietnamagriculture
      POSTGRES_DB: vietnam_agriculture
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vietnamagriculture -d vietnam_agriculture" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agri_network

  backend:
    build: ./backend
    container_name: vietnam_agri_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: app-db
      DB_USER: vietnamagriculture
      DB_PASS: vietnamagriculture
      DB_PORT: 5432
      DB_NAME: vietnam_agriculture
    depends_on:
      app-db:
        condition: service_healthy
    networks:
      - agri_network

  db-seeder:
    build: ./backend
    container_name: vietnam_agri_seeder
    environment:
      DB_HOST: app-db
      DB_USER: vietnamagriculture
      DB_PASS: vietnamagriculture
      DB_PORT: 5432
      DB_NAME: vietnam_agriculture
    depends_on:
      - backend
    command: [ "python", "seed_db.py" ]
    networks:
      - agri_network

  frontend:
    build: ./frontend
    container_name: vietnam_agri_frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - agri_network

volumes:
  postgres_data:


networks:
  agri_network:
    driver: bridge
